version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: tuagenda_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tuagenda_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
